name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full history (needed for pull --rebase)
          lfs: true       # If you're using Git LFS

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull & Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add Hugging Face remote with authentication
          git remote add hf https://abhipisal1998:$HF_TOKEN@huggingface.co/spaces/abhipisal1998/Search_Engine_llm

          # Pull changes from Hugging Face main with rebase to avoid conflicts
          git pull hf main --rebase

          # Now push local main branch to Hugging Face
          git push hf main
