name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Force Push to Hugging Face Hub (overwrite remote)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://abhipisal1998:$HF_TOKEN@huggingface.co/spaces/abhipisal1998/Search_Engine_llm
          git fetch hf
          git reset --hard origin/main   # Local reset to match GitHub repo
          git push hf main --force
