name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to fetch all history for rebase
          lfs: true       # If using Git LFS (optional)

      - name: Set up Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull & Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://abhipisal1998:$HF_TOKEN@huggingface.co/spaces/abhipisal1998/Search_Engine_llm
          git pull hf main --rebase
          git push hf main
